services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:Iamadotapro123@db:5432/food_recipes
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "80:80"

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Iamadotapro123
      POSTGRES_DB: food_recipes
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
