services:
  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    environment:
      - DATABASE_URL=postgres://postgres:Iamadotapro123@db:5432/food_recipes
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - db
    command: node server.js  # Changed from npm run dev to node server.js

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"  # Changed to 3000 for Vite's default port
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - backend

  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Iamadotapro123
      POSTGRES_DB: food_recipes
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
